[package]
name = "model3d-gltf"
version = "0.0.1"
edition = "2021"

[features]

[dependencies]
base64 = "0.22.1"
geo-nd   = "0.1.0"
indent-display = "0.1.1"
model3d-base = { path="../model3d-base" }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
thiserror = "1.0.61"
